services:
  postgres:
    image: postgres:17
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-app}"
      POSTGRES_USER: "${DB_USER:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-root}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
